# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'cfg.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QGroupBox, QListWidget,
    QListWidgetItem, QPushButton, QSizePolicy, QTextEdit,
    QWidget)

class Ui_CFG(object):
    def setupUi(self, CFG):
        if not CFG.objectName():
            CFG.setObjectName(u"CFG")
        CFG.resize(1185, 873)
        self.ListBox = QGroupBox(CFG)
        self.ListBox.setObjectName(u"ListBox")
        self.ListBox.setGeometry(QRect(20, 0, 471, 851))
        font = QFont()
        font.setBold(True)
        self.ListBox.setFont(font)
        self.listWidget_UnitList = QListWidget(self.ListBox)
        self.listWidget_UnitList.setObjectName(u"listWidget_UnitList")
        self.listWidget_UnitList.setGeometry(QRect(10, 20, 451, 821))
        font1 = QFont()
        font1.setPointSize(8)
        font1.setBold(True)
        self.listWidget_UnitList.setFont(font1)
        self.groupBox_1 = QGroupBox(CFG)
        self.groupBox_1.setObjectName(u"groupBox_1")
        self.groupBox_1.setGeometry(QRect(510, 0, 631, 171))
        self.groupBox_1.setFont(font)
        self.colorBox_1 = QGroupBox(self.groupBox_1)
        self.colorBox_1.setObjectName(u"colorBox_1")
        self.colorBox_1.setGeometry(QRect(510, 50, 111, 61))
        self.colorBox_1.setFont(font)
        self.selectButton_1 = QPushButton(self.colorBox_1)
        self.selectButton_1.setObjectName(u"selectButton_1")
        self.selectButton_1.setGeometry(QRect(0, 20, 111, 24))
        self.selectButton_1.setFont(font)
        self.listWidget_G1 = QListWidget(self.groupBox_1)
        self.listWidget_G1.setObjectName(u"listWidget_G1")
        self.listWidget_G1.setGeometry(QRect(10, 20, 481, 141))
        font2 = QFont()
        font2.setPointSize(7)
        font2.setBold(True)
        self.listWidget_G1.setFont(font2)
        self.groupBox_2 = QGroupBox(CFG)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(510, 170, 631, 171))
        self.groupBox_2.setFont(font)
        self.colorBox_2 = QGroupBox(self.groupBox_2)
        self.colorBox_2.setObjectName(u"colorBox_2")
        self.colorBox_2.setGeometry(QRect(510, 60, 111, 61))
        self.colorBox_2.setFont(font)
        self.selectButton_2 = QPushButton(self.colorBox_2)
        self.selectButton_2.setObjectName(u"selectButton_2")
        self.selectButton_2.setGeometry(QRect(0, 20, 111, 24))
        self.selectButton_2.setFont(font)
        self.listWidget_G2 = QListWidget(self.groupBox_2)
        self.listWidget_G2.setObjectName(u"listWidget_G2")
        self.listWidget_G2.setGeometry(QRect(10, 20, 481, 141))
        self.listWidget_G2.setFont(font2)
        self.groupBox_3 = QGroupBox(CFG)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(510, 340, 631, 171))
        self.groupBox_3.setFont(font)
        self.colorBox_3 = QGroupBox(self.groupBox_3)
        self.colorBox_3.setObjectName(u"colorBox_3")
        self.colorBox_3.setGeometry(QRect(510, 50, 111, 61))
        self.colorBox_3.setFont(font)
        self.selectButton_3 = QPushButton(self.colorBox_3)
        self.selectButton_3.setObjectName(u"selectButton_3")
        self.selectButton_3.setGeometry(QRect(0, 20, 111, 24))
        self.selectButton_3.setFont(font)
        self.listWidget_G3 = QListWidget(self.groupBox_3)
        self.listWidget_G3.setObjectName(u"listWidget_G3")
        self.listWidget_G3.setGeometry(QRect(10, 20, 481, 141))
        self.listWidget_G3.setFont(font2)
        self.groupBox_4 = QGroupBox(CFG)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(510, 510, 631, 171))
        self.groupBox_4.setFont(font)
        self.colorBox_4 = QGroupBox(self.groupBox_4)
        self.colorBox_4.setObjectName(u"colorBox_4")
        self.colorBox_4.setGeometry(QRect(510, 60, 111, 61))
        self.colorBox_4.setFont(font)
        self.selectButton_4 = QPushButton(self.colorBox_4)
        self.selectButton_4.setObjectName(u"selectButton_4")
        self.selectButton_4.setGeometry(QRect(0, 20, 111, 24))
        self.selectButton_4.setFont(font)
        self.listWidget_G4 = QListWidget(self.groupBox_4)
        self.listWidget_G4.setObjectName(u"listWidget_G4")
        self.listWidget_G4.setGeometry(QRect(10, 20, 481, 141))
        self.listWidget_G4.setFont(font2)
        self.groupBox_5 = QGroupBox(CFG)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(510, 680, 631, 171))
        self.groupBox_5.setFont(font)
        self.doneButton = QPushButton(self.groupBox_5)
        self.doneButton.setObjectName(u"doneButton")
        self.doneButton.setGeometry(QRect(10, 100, 611, 31))
        self.doneButton.setFont(font)
        self.cancelButton = QPushButton(self.groupBox_5)
        self.cancelButton.setObjectName(u"cancelButton")
        self.cancelButton.setGeometry(QRect(10, 130, 611, 31))
        self.cancelButton.setFont(font)
        self.MessageBox = QTextEdit(self.groupBox_5)
        self.MessageBox.setObjectName(u"MessageBox")
        self.MessageBox.setGeometry(QRect(10, 23, 611, 71))
        self.MessageBox.setFont(font)

        self.retranslateUi(CFG)

        QMetaObject.connectSlotsByName(CFG)
    # setupUi

    def retranslateUi(self, CFG):
        CFG.setWindowTitle(QCoreApplication.translate("CFG", u"Dialog", None))
        self.ListBox.setTitle(QCoreApplication.translate("CFG", u"List Of Unit", None))
        self.groupBox_1.setTitle(QCoreApplication.translate("CFG", u"Group 1", None))
        self.colorBox_1.setTitle(QCoreApplication.translate("CFG", u"Color", None))
        self.selectButton_1.setText(QCoreApplication.translate("CFG", u"Select", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("CFG", u"Group 2", None))
        self.colorBox_2.setTitle(QCoreApplication.translate("CFG", u"Color", None))
        self.selectButton_2.setText(QCoreApplication.translate("CFG", u"Select", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("CFG", u"Group 3", None))
        self.colorBox_3.setTitle(QCoreApplication.translate("CFG", u"Color", None))
        self.selectButton_3.setText(QCoreApplication.translate("CFG", u"Select", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("CFG", u"Group 4", None))
        self.colorBox_4.setTitle(QCoreApplication.translate("CFG", u"Color", None))
        self.selectButton_4.setText(QCoreApplication.translate("CFG", u"Select", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("CFG", u"Conclude/MessageBox", None))
        self.doneButton.setText(QCoreApplication.translate("CFG", u"Done", None))
        self.cancelButton.setText(QCoreApplication.translate("CFG", u"Cancel", None))
    # retranslateUi

