# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGroupBox, QLabel, QLineEdit, QListView,
    QListWidget, QListWidgetItem, QProgressBar, QPushButton,
    QSizePolicy, QTabWidget, QTextEdit, QToolButton,
    QWidget)

class Ui_Main(object):
    def setupUi(self, Main):
        if not Main.objectName():
            Main.setObjectName(u"Main")
        Main.resize(1010, 899)
        font = QFont()
        font.setBold(True)
        font.setKerning(True)
        Main.setFont(font)
        self.tabWidget = QTabWidget(Main)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(12, 20, 991, 871))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.firstFrame = QFrame(self.tab)
        self.firstFrame.setObjectName(u"firstFrame")
        self.firstFrame.setGeometry(QRect(0, 0, 981, 841))
        self.firstFrame.setAutoFillBackground(False)
        self.firstFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.firstFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.S_Parameter_groupBox = QGroupBox(self.firstFrame)
        self.S_Parameter_groupBox.setObjectName(u"S_Parameter_groupBox")
        self.S_Parameter_groupBox.setGeometry(QRect(10, 10, 341, 491))
        self.S_Parameter_groupBox.setFont(font)
        self.Filter_groupBox = QGroupBox(self.S_Parameter_groupBox)
        self.Filter_groupBox.setObjectName(u"Filter_groupBox")
        self.Filter_groupBox.setGeometry(QRect(10, 20, 321, 61))
        font1 = QFont()
        font1.setBold(True)
        font1.setKerning(False)
        self.Filter_groupBox.setFont(font1)
        self.SFilter_lineEdit = QLineEdit(self.Filter_groupBox)
        self.SFilter_lineEdit.setObjectName(u"SFilter_lineEdit")
        self.SFilter_lineEdit.setGeometry(QRect(10, 20, 141, 31))
        self.SOnly_checkBox = QCheckBox(self.Filter_groupBox)
        self.SOnly_checkBox.setObjectName(u"SOnly_checkBox")
        self.SOnly_checkBox.setGeometry(QRect(160, 25, 61, 20))
        font2 = QFont()
        font2.setBold(False)
        font2.setKerning(False)
        self.SOnly_checkBox.setFont(font2)
        self.FOnly_checkBox = QCheckBox(self.Filter_groupBox)
        self.FOnly_checkBox.setObjectName(u"FOnly_checkBox")
        self.FOnly_checkBox.setGeometry(QRect(230, 25, 71, 20))
        self.FOnly_checkBox.setFont(font2)
        self.listWidget = QListWidget(self.S_Parameter_groupBox)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(10, 90, 321, 391))
        self.listWidget.setFont(font)
        self.ModuleCover_groupBox = QGroupBox(self.firstFrame)
        self.ModuleCover_groupBox.setObjectName(u"ModuleCover_groupBox")
        self.ModuleCover_groupBox.setGeometry(QRect(360, 10, 611, 711))
        self.ModuleCover_groupBox.setFont(font)
        self.Module_groupBox = QGroupBox(self.ModuleCover_groupBox)
        self.Module_groupBox.setObjectName(u"Module_groupBox")
        self.Module_groupBox.setGeometry(QRect(10, 20, 591, 161))
        self.Module_groupBox.setFont(font)
        self.ZipDir_lineEdit = QLineEdit(self.Module_groupBox)
        self.ZipDir_lineEdit.setObjectName(u"ZipDir_lineEdit")
        self.ZipDir_lineEdit.setGeometry(QRect(20, 26, 531, 31))
        self.ZipDir_lineEdit.setFont(font)
        self.Extract_toolButton = QToolButton(self.Module_groupBox)
        self.Extract_toolButton.setObjectName(u"Extract_toolButton")
        self.Extract_toolButton.setGeometry(QRect(560, 35, 21, 22))
        font3 = QFont()
        font3.setPointSize(9)
        font3.setBold(True)
        font3.setKerning(True)
        self.Extract_toolButton.setFont(font3)
        self.FileType_groupBox = QGroupBox(self.Module_groupBox)
        self.FileType_groupBox.setObjectName(u"FileType_groupBox")
        self.FileType_groupBox.setGeometry(QRect(20, 60, 561, 91))
        self.FileType_groupBox.setFont(font1)
        self.fileType_comboBox = QComboBox(self.FileType_groupBox)
        self.fileType_comboBox.setObjectName(u"fileType_comboBox")
        self.fileType_comboBox.setGeometry(QRect(280, 20, 141, 31))
        self.fileType_comboBox.setFont(font2)
        self.compileButton = QPushButton(self.FileType_groupBox)
        self.compileButton.setObjectName(u"compileButton")
        self.compileButton.setGeometry(QRect(430, 20, 111, 31))
        self.compileButton.setAutoFillBackground(False)
        self.button_ReplaceCFG = QPushButton(self.FileType_groupBox)
        self.button_ReplaceCFG.setObjectName(u"button_ReplaceCFG")
        self.button_ReplaceCFG.setGeometry(QRect(10, 56, 121, 31))
        self.button_ReplaceCFG.setAutoFillBackground(False)
        self.Overwrite_Link = QLabel(self.FileType_groupBox)
        self.Overwrite_Link.setObjectName(u"Overwrite_Link")
        self.Overwrite_Link.setGeometry(QRect(390, 60, 81, 20))
        font4 = QFont()
        font4.setPointSize(8)
        font4.setBold(False)
        font4.setItalic(True)
        font4.setKerning(True)
        self.Overwrite_Link.setFont(font4)
        self.TPType_comboBox = QComboBox(self.FileType_groupBox)
        self.TPType_comboBox.setObjectName(u"TPType_comboBox")
        self.TPType_comboBox.setGeometry(QRect(85, 20, 111, 31))
        self.TPType_comboBox.setFont(font2)
        self.TestCode = QLabel(self.FileType_groupBox)
        self.TestCode.setObjectName(u"TestCode")
        self.TestCode.setGeometry(QRect(10, 24, 61, 21))
        self.TestCode.setFont(font1)
        self.FileType = QLabel(self.FileType_groupBox)
        self.FileType.setObjectName(u"FileType")
        self.FileType.setGeometry(QRect(214, 24, 61, 21))
        self.FileType.setFont(font1)
        self.dataset_Link = QLabel(self.FileType_groupBox)
        self.dataset_Link.setObjectName(u"dataset_Link")
        self.dataset_Link.setGeometry(QRect(480, 60, 71, 20))
        self.dataset_Link.setFont(font4)
        self.button_HeaderEdit = QPushButton(self.FileType_groupBox)
        self.button_HeaderEdit.setObjectName(u"button_HeaderEdit")
        self.button_HeaderEdit.setGeometry(QRect(140, 56, 121, 31))
        self.button_HeaderEdit.setAutoFillBackground(False)
        self.RefreshMemory_Button = QPushButton(self.FileType_groupBox)
        self.RefreshMemory_Button.setObjectName(u"RefreshMemory_Button")
        self.RefreshMemory_Button.setGeometry(QRect(270, 56, 111, 31))
        font5 = QFont()
        font5.setPointSize(8)
        font5.setBold(False)
        font5.setKerning(False)
        self.RefreshMemory_Button.setFont(font5)
        self.RefreshMemory_Button.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.RefreshMemory_Button.setFlat(False)
        self.ManualPloting_groupBox = QGroupBox(self.ModuleCover_groupBox)
        self.ManualPloting_groupBox.setObjectName(u"ManualPloting_groupBox")
        self.ManualPloting_groupBox.setGeometry(QRect(10, 180, 591, 311))
        self.ManualPloting_groupBox.setFont(font)
        self.Manual_lineEdit = QLineEdit(self.ManualPloting_groupBox)
        self.Manual_lineEdit.setObjectName(u"Manual_lineEdit")
        self.Manual_lineEdit.setGeometry(QRect(10, 20, 521, 31))
        self.Manual_lineEdit.setFont(font)
        self.Plot_toolButton = QToolButton(self.ManualPloting_groupBox)
        self.Plot_toolButton.setObjectName(u"Plot_toolButton")
        self.Plot_toolButton.setGeometry(QRect(540, 35, 21, 22))
        self.Plot_toolButton.setFont(font)
        self.ColorGroupOption_groupBox = QGroupBox(self.ManualPloting_groupBox)
        self.ColorGroupOption_groupBox.setObjectName(u"ColorGroupOption_groupBox")
        self.ColorGroupOption_groupBox.setGeometry(QRect(10, 60, 571, 241))
        self.ColorGroupOption_groupBox.setFont(font1)
        self.SearchRegex_lineEdit = QLineEdit(self.ColorGroupOption_groupBox)
        self.SearchRegex_lineEdit.setObjectName(u"SearchRegex_lineEdit")
        self.SearchRegex_lineEdit.setGeometry(QRect(100, 154, 311, 31))
        self.label = QLabel(self.ColorGroupOption_groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 156, 81, 21))
        self.label.setFont(font1)
        self.ColorCode_lineEdit = QLineEdit(self.ColorGroupOption_groupBox)
        self.ColorCode_lineEdit.setObjectName(u"ColorCode_lineEdit")
        self.ColorCode_lineEdit.setGeometry(QRect(100, 197, 311, 31))
        self.label_2 = QLabel(self.ColorGroupOption_groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 199, 81, 21))
        self.label_2.setFont(font1)
        self.Execute_groupBox = QGroupBox(self.ColorGroupOption_groupBox)
        self.Execute_groupBox.setObjectName(u"Execute_groupBox")
        self.Execute_groupBox.setGeometry(QRect(330, 20, 231, 111))
        self.Execute_groupBox.setFont(font1)
        self.plotButton = QPushButton(self.Execute_groupBox)
        self.plotButton.setObjectName(u"plotButton")
        self.plotButton.setGeometry(QRect(130, 60, 91, 41))
        self.plotButton.setFont(font5)
        self.LoadButton = QPushButton(self.Execute_groupBox)
        self.LoadButton.setObjectName(u"LoadButton")
        self.LoadButton.setGeometry(QRect(130, 20, 91, 35))
        self.LoadButton.setFont(font5)
        self.LoadButton.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.LoadButton.setFlat(False)
        self.XStep = QLabel(self.Execute_groupBox)
        self.XStep.setObjectName(u"XStep")
        self.XStep.setGeometry(QRect(7, 28, 41, 21))
        font6 = QFont()
        font6.setPointSize(8)
        font6.setBold(True)
        font6.setKerning(False)
        self.XStep.setFont(font6)
        self.YStep = QLabel(self.Execute_groupBox)
        self.YStep.setObjectName(u"YStep")
        self.YStep.setGeometry(QRect(7, 70, 41, 21))
        self.YStep.setFont(font6)
        self.XsteplineEdit = QLineEdit(self.Execute_groupBox)
        self.XsteplineEdit.setObjectName(u"XsteplineEdit")
        self.XsteplineEdit.setGeometry(QRect(50, 28, 71, 21))
        self.XsteplineEdit.setFont(font)
        self.YsteplineEdit = QLineEdit(self.Execute_groupBox)
        self.YsteplineEdit.setObjectName(u"YsteplineEdit")
        self.YsteplineEdit.setGeometry(QRect(50, 70, 71, 21))
        self.YsteplineEdit.setFont(font)
        self.listView = QListView(self.ColorGroupOption_groupBox)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(-360, -160, 301, 581))
        self.Selection_groupBox = QGroupBox(self.ColorGroupOption_groupBox)
        self.Selection_groupBox.setObjectName(u"Selection_groupBox")
        self.Selection_groupBox.setGeometry(QRect(10, 20, 311, 111))
        self.Selection_groupBox.setFont(font1)
        self.Selection_groupBox.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.cfgFile_checkBox = QCheckBox(self.Selection_groupBox)
        self.cfgFile_checkBox.setObjectName(u"cfgFile_checkBox")
        self.cfgFile_checkBox.setGeometry(QRect(90, 20, 71, 20))
        self.cfgFile_checkBox.setFont(font2)
        self.ByUnit_checkBox = QCheckBox(self.Selection_groupBox)
        self.ByUnit_checkBox.setObjectName(u"ByUnit_checkBox")
        self.ByUnit_checkBox.setGeometry(QRect(8, 20, 71, 20))
        self.ByUnit_checkBox.setFont(font2)
        self.Legend_checkBox = QCheckBox(self.Selection_groupBox)
        self.Legend_checkBox.setObjectName(u"Legend_checkBox")
        self.Legend_checkBox.setGeometry(QRect(92, 50, 61, 20))
        self.Legend_checkBox.setFont(font2)
        self.ByLot_checkBox = QCheckBox(self.Selection_groupBox)
        self.ByLot_checkBox.setObjectName(u"ByLot_checkBox")
        self.ByLot_checkBox.setGeometry(QRect(8, 50, 81, 20))
        self.ByLot_checkBox.setFont(font2)
        self.cfgUI_checkBox = QCheckBox(self.Selection_groupBox)
        self.cfgUI_checkBox.setObjectName(u"cfgUI_checkBox")
        self.cfgUI_checkBox.setGeometry(QRect(165, 20, 61, 20))
        self.cfgUI_checkBox.setFont(font2)
        self.SpecLine_checkBox = QCheckBox(self.Selection_groupBox)
        self.SpecLine_checkBox.setObjectName(u"SpecLine_checkBox")
        self.SpecLine_checkBox.setGeometry(QRect(165, 50, 71, 20))
        self.SpecLine_checkBox.setFont(font2)
        self.PopulatedUnitList_button = QPushButton(self.Selection_groupBox)
        self.PopulatedUnitList_button.setObjectName(u"PopulatedUnitList_button")
        self.PopulatedUnitList_button.setGeometry(QRect(6, 76, 191, 31))
        font7 = QFont()
        font7.setBold(False)
        font7.setItalic(True)
        font7.setUnderline(False)
        font7.setStrikeOut(False)
        font7.setKerning(False)
        self.PopulatedUnitList_button.setFont(font7)
        self.PopulatedUnitList_button.setAutoFillBackground(False)
        self.ManualHover_checkBox = QCheckBox(self.Selection_groupBox)
        self.ManualHover_checkBox.setObjectName(u"ManualHover_checkBox")
        self.ManualHover_checkBox.setGeometry(QRect(244, 20, 61, 20))
        self.ManualHover_checkBox.setFont(font2)
        self.ByUnit_Link = QLabel(self.Selection_groupBox)
        self.ByUnit_Link.setObjectName(u"ByUnit_Link")
        self.ByUnit_Link.setGeometry(QRect(208, 85, 81, 16))
        self.ByUnit_Link.setFont(font4)
        self.marker_checkBox = QCheckBox(self.Selection_groupBox)
        self.marker_checkBox.setObjectName(u"marker_checkBox")
        self.marker_checkBox.setGeometry(QRect(244, 50, 61, 20))
        self.marker_checkBox.setFont(font2)
        self.RegexControl_groupBox = QGroupBox(self.ColorGroupOption_groupBox)
        self.RegexControl_groupBox.setObjectName(u"RegexControl_groupBox")
        self.RegexControl_groupBox.setGeometry(QRect(420, 144, 141, 89))
        font8 = QFont()
        font8.setPointSize(9)
        font8.setBold(True)
        font8.setKerning(False)
        self.RegexControl_groupBox.setFont(font8)
        self.LOTApplyButton = QPushButton(self.RegexControl_groupBox)
        self.LOTApplyButton.setObjectName(u"LOTApplyButton")
        self.LOTApplyButton.setGeometry(QRect(10, 52, 121, 31))
        self.LOTApplyButton.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.LOTApplyButton.setFlat(False)
        self.FilterLotList_comboBox = QComboBox(self.RegexControl_groupBox)
        self.FilterLotList_comboBox.setObjectName(u"FilterLotList_comboBox")
        self.FilterLotList_comboBox.setGeometry(QRect(10, 18, 121, 31))
        font9 = QFont()
        font9.setPointSize(9)
        font9.setBold(False)
        font9.setKerning(False)
        self.FilterLotList_comboBox.setFont(font9)
        self.Automation_groupBox = QGroupBox(self.ModuleCover_groupBox)
        self.Automation_groupBox.setObjectName(u"Automation_groupBox")
        self.Automation_groupBox.setGeometry(QRect(10, 500, 591, 201))
        self.Automation_groupBox.setFont(font)
        self.Batch_groupBox = QGroupBox(self.Automation_groupBox)
        self.Batch_groupBox.setObjectName(u"Batch_groupBox")
        self.Batch_groupBox.setGeometry(QRect(10, 20, 571, 174))
        self.Batch_groupBox.setFont(font1)
        self.Generator_comboBox = QComboBox(self.Batch_groupBox)
        self.Generator_comboBox.setObjectName(u"Generator_comboBox")
        self.Generator_comboBox.setGeometry(QRect(60, 30, 351, 31))
        self.CapturedButton = QPushButton(self.Batch_groupBox)
        self.CapturedButton.setObjectName(u"CapturedButton")
        self.CapturedButton.setGeometry(QRect(420, 67, 141, 31))
        self.PPTButton = QPushButton(self.Batch_groupBox)
        self.PPTButton.setObjectName(u"PPTButton")
        self.PPTButton.setGeometry(QRect(420, 103, 141, 31))
        self.label_21 = QLabel(self.Batch_groupBox)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(13, 35, 41, 16))
        self.label_21.setFont(font1)
        self.AutoSpecLine_checkBox = QCheckBox(self.Batch_groupBox)
        self.AutoSpecLine_checkBox.setObjectName(u"AutoSpecLine_checkBox")
        self.AutoSpecLine_checkBox.setGeometry(QRect(13, 70, 81, 20))
        self.ServiceButton = QPushButton(self.Batch_groupBox)
        self.ServiceButton.setObjectName(u"ServiceButton")
        self.ServiceButton.setGeometry(QRect(10, 138, 481, 31))
        self.ServiceButton.setFont(font1)
        self.RefreshFirstButton = QPushButton(self.Batch_groupBox)
        self.RefreshFirstButton.setObjectName(u"RefreshFirstButton")
        self.RefreshFirstButton.setGeometry(QRect(420, 30, 141, 31))
        self.AutoByLot_checkBox = QCheckBox(self.Batch_groupBox)
        self.AutoByLot_checkBox.setObjectName(u"AutoByLot_checkBox")
        self.AutoByLot_checkBox.setGeometry(QRect(180, 70, 81, 20))
        self.AutoByUnit_checkBox = QCheckBox(self.Batch_groupBox)
        self.AutoByUnit_checkBox.setObjectName(u"AutoByUnit_checkBox")
        self.AutoByUnit_checkBox.setGeometry(QRect(98, 70, 71, 20))
        self.LotModuleButton = QPushButton(self.Batch_groupBox)
        self.LotModuleButton.setObjectName(u"LotModuleButton")
        self.LotModuleButton.setGeometry(QRect(10, 103, 191, 31))
        font10 = QFont()
        font10.setBold(False)
        font10.setItalic(True)
        font10.setKerning(False)
        self.LotModuleButton.setFont(font10)
        self.PPT_Link = QLabel(self.Batch_groupBox)
        self.PPT_Link.setObjectName(u"PPT_Link")
        self.PPT_Link.setGeometry(QRect(500, 144, 51, 16))
        self.PPT_Link.setFont(font4)
        self.Batch_Link = QLabel(self.Batch_groupBox)
        self.Batch_Link.setObjectName(u"Batch_Link")
        self.Batch_Link.setGeometry(QRect(349, 72, 61, 16))
        self.Batch_Link.setFont(font4)
        self.ByLot_Link = QLabel(self.Batch_groupBox)
        self.ByLot_Link.setObjectName(u"ByLot_Link")
        self.ByLot_Link.setGeometry(QRect(349, 110, 71, 16))
        self.ByLot_Link.setFont(font4)
        self.GeneratorGroup_comboBox = QComboBox(self.Batch_groupBox)
        self.GeneratorGroup_comboBox.setObjectName(u"GeneratorGroup_comboBox")
        self.GeneratorGroup_comboBox.setGeometry(QRect(210, 103, 111, 31))
        self.groupBox_3 = QGroupBox(self.firstFrame)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 730, 961, 101))
        self.groupBox_3.setFont(font)
        self.progressBar = QProgressBar(self.groupBox_3)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(840, 50, 111, 11))
        font11 = QFont()
        font11.setPointSize(8)
        font11.setBold(True)
        font11.setItalic(False)
        font11.setKerning(False)
        self.progressBar.setFont(font11)
        self.progressBar.setValue(0)
        self.ProgressBar_textEdit = QTextEdit(self.groupBox_3)
        self.ProgressBar_textEdit.setObjectName(u"ProgressBar_textEdit")
        self.ProgressBar_textEdit.setGeometry(QRect(8, 20, 812, 71))
        self.ProgressBar_textEdit.setFont(font10)
        self.Setting_groupBox = QGroupBox(self.firstFrame)
        self.Setting_groupBox.setObjectName(u"Setting_groupBox")
        self.Setting_groupBox.setGeometry(QRect(10, 570, 341, 151))
        self.Setting_groupBox.setFont(font)
        self.Formula_RefreshButton = QPushButton(self.Setting_groupBox)
        self.Formula_RefreshButton.setObjectName(u"Formula_RefreshButton")
        self.Formula_RefreshButton.setGeometry(QRect(230, 70, 91, 31))
        self.Formula_comboBox = QComboBox(self.Setting_groupBox)
        self.Formula_comboBox.setObjectName(u"Formula_comboBox")
        self.Formula_comboBox.setGeometry(QRect(50, 30, 271, 31))
        self.Formula_comboBox.setFont(font2)
        self.Formula = QLabel(self.Setting_groupBox)
        self.Formula.setObjectName(u"Formula")
        self.Formula.setGeometry(QRect(5, 30, 41, 21))
        self.Formula.setFont(font1)
        self.EditFormulaButton = QPushButton(self.Setting_groupBox)
        self.EditFormulaButton.setObjectName(u"EditFormulaButton")
        self.EditFormulaButton.setGeometry(QRect(10, 70, 211, 31))
        self.FormulaExecuteButton = QPushButton(self.Setting_groupBox)
        self.FormulaExecuteButton.setObjectName(u"FormulaExecuteButton")
        self.FormulaExecuteButton.setGeometry(QRect(10, 110, 311, 31))
        self.FreqRange_groupBox = QGroupBox(self.firstFrame)
        self.FreqRange_groupBox.setObjectName(u"FreqRange_groupBox")
        self.FreqRange_groupBox.setGeometry(QRect(10, 510, 341, 51))
        self.FreqRange_groupBox.setFont(font1)
        self.Startfreq_lineEdit = QLineEdit(self.FreqRange_groupBox)
        self.Startfreq_lineEdit.setObjectName(u"Startfreq_lineEdit")
        self.Startfreq_lineEdit.setGeometry(QRect(60, 20, 111, 21))
        self.Startfreq_lineEdit_2 = QLineEdit(self.FreqRange_groupBox)
        self.Startfreq_lineEdit_2.setObjectName(u"Startfreq_lineEdit_2")
        self.Startfreq_lineEdit_2.setGeometry(QRect(220, 20, 111, 21))
        self.Start_label = QLabel(self.FreqRange_groupBox)
        self.Start_label.setObjectName(u"Start_label")
        self.Start_label.setGeometry(QRect(10, 20, 31, 16))
        self.Start_label.setFont(font1)
        self.Start_label_2 = QLabel(self.FreqRange_groupBox)
        self.Start_label_2.setObjectName(u"Start_label_2")
        self.Start_label_2.setGeometry(QRect(180, 20, 31, 16))
        self.Start_label_2.setFont(font1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.secondFrame = QFrame(self.tab_2)
        self.secondFrame.setObjectName(u"secondFrame")
        self.secondFrame.setGeometry(QRect(0, 0, 981, 831))
        self.secondFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.secondFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.groupBox_12 = QGroupBox(self.secondFrame)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(20, 10, 171, 811))
        font12 = QFont()
        font12.setPointSize(8)
        font12.setBold(True)
        font12.setKerning(True)
        self.groupBox_12.setFont(font12)
        self.CFGF1_comboBox = QComboBox(self.groupBox_12)
        self.CFGF1_comboBox.setObjectName(u"CFGF1_comboBox")
        self.CFGF1_comboBox.setGeometry(QRect(80, 30, 81, 22))
        self.CFGF1_comboBox.setFont(font12)
        self.colorLabel1 = QLabel(self.groupBox_12)
        self.colorLabel1.setObjectName(u"colorLabel1")
        self.colorLabel1.setGeometry(QRect(10, 30, 61, 20))
        self.colorLabel1.setFont(font12)
        self.colorLabel2 = QLabel(self.groupBox_12)
        self.colorLabel2.setObjectName(u"colorLabel2")
        self.colorLabel2.setGeometry(QRect(10, 60, 61, 20))
        self.colorLabel2.setFont(font12)
        self.colorLabel3 = QLabel(self.groupBox_12)
        self.colorLabel3.setObjectName(u"colorLabel3")
        self.colorLabel3.setGeometry(QRect(10, 90, 61, 20))
        self.colorLabel3.setFont(font12)
        self.colorLabel4 = QLabel(self.groupBox_12)
        self.colorLabel4.setObjectName(u"colorLabel4")
        self.colorLabel4.setGeometry(QRect(10, 120, 61, 20))
        self.colorLabel4.setFont(font12)
        self.colorLabel5 = QLabel(self.groupBox_12)
        self.colorLabel5.setObjectName(u"colorLabel5")
        self.colorLabel5.setGeometry(QRect(10, 150, 61, 20))
        self.colorLabel5.setFont(font12)
        self.colorLabel6 = QLabel(self.groupBox_12)
        self.colorLabel6.setObjectName(u"colorLabel6")
        self.colorLabel6.setGeometry(QRect(10, 180, 61, 20))
        self.colorLabel6.setFont(font12)
        self.colorLabel7 = QLabel(self.groupBox_12)
        self.colorLabel7.setObjectName(u"colorLabel7")
        self.colorLabel7.setGeometry(QRect(10, 210, 61, 20))
        self.colorLabel7.setFont(font12)
        self.colorLabel8 = QLabel(self.groupBox_12)
        self.colorLabel8.setObjectName(u"colorLabel8")
        self.colorLabel8.setGeometry(QRect(10, 240, 61, 20))
        self.colorLabel8.setFont(font12)
        self.colorLabel9 = QLabel(self.groupBox_12)
        self.colorLabel9.setObjectName(u"colorLabel9")
        self.colorLabel9.setGeometry(QRect(10, 270, 61, 20))
        self.colorLabel9.setFont(font12)
        self.colorLabel10 = QLabel(self.groupBox_12)
        self.colorLabel10.setObjectName(u"colorLabel10")
        self.colorLabel10.setGeometry(QRect(10, 300, 61, 20))
        self.colorLabel10.setFont(font12)
        self.colorLabel11 = QLabel(self.groupBox_12)
        self.colorLabel11.setObjectName(u"colorLabel11")
        self.colorLabel11.setGeometry(QRect(10, 330, 61, 20))
        self.colorLabel11.setFont(font12)
        self.colorLabel12 = QLabel(self.groupBox_12)
        self.colorLabel12.setObjectName(u"colorLabel12")
        self.colorLabel12.setGeometry(QRect(10, 360, 61, 20))
        self.colorLabel12.setFont(font12)
        self.colorLabel13 = QLabel(self.groupBox_12)
        self.colorLabel13.setObjectName(u"colorLabel13")
        self.colorLabel13.setGeometry(QRect(10, 390, 61, 20))
        self.colorLabel13.setFont(font12)
        self.colorLabel14 = QLabel(self.groupBox_12)
        self.colorLabel14.setObjectName(u"colorLabel14")
        self.colorLabel14.setGeometry(QRect(10, 420, 61, 20))
        self.colorLabel14.setFont(font12)
        self.colorLabel15 = QLabel(self.groupBox_12)
        self.colorLabel15.setObjectName(u"colorLabel15")
        self.colorLabel15.setGeometry(QRect(10, 450, 61, 20))
        self.colorLabel15.setFont(font12)
        self.colorLabel16 = QLabel(self.groupBox_12)
        self.colorLabel16.setObjectName(u"colorLabel16")
        self.colorLabel16.setGeometry(QRect(10, 480, 61, 20))
        self.colorLabel16.setFont(font12)
        self.colorLabel17 = QLabel(self.groupBox_12)
        self.colorLabel17.setObjectName(u"colorLabel17")
        self.colorLabel17.setGeometry(QRect(10, 510, 61, 20))
        self.colorLabel17.setFont(font12)
        self.colorLabel18 = QLabel(self.groupBox_12)
        self.colorLabel18.setObjectName(u"colorLabel18")
        self.colorLabel18.setGeometry(QRect(10, 540, 61, 20))
        self.colorLabel18.setFont(font12)
        self.colorLabel19 = QLabel(self.groupBox_12)
        self.colorLabel19.setObjectName(u"colorLabel19")
        self.colorLabel19.setGeometry(QRect(10, 570, 61, 20))
        self.colorLabel19.setFont(font12)
        self.colorLabel20 = QLabel(self.groupBox_12)
        self.colorLabel20.setObjectName(u"colorLabel20")
        self.colorLabel20.setGeometry(QRect(10, 600, 61, 20))
        self.colorLabel20.setFont(font12)
        self.colorLabel21 = QLabel(self.groupBox_12)
        self.colorLabel21.setObjectName(u"colorLabel21")
        self.colorLabel21.setGeometry(QRect(10, 630, 61, 20))
        self.colorLabel21.setFont(font12)
        self.colorLabel22 = QLabel(self.groupBox_12)
        self.colorLabel22.setObjectName(u"colorLabel22")
        self.colorLabel22.setGeometry(QRect(10, 660, 61, 20))
        self.colorLabel22.setFont(font12)
        self.colorLabel23 = QLabel(self.groupBox_12)
        self.colorLabel23.setObjectName(u"colorLabel23")
        self.colorLabel23.setGeometry(QRect(10, 690, 61, 20))
        self.colorLabel23.setFont(font12)
        self.CFGDefaultButton = QPushButton(self.groupBox_12)
        self.CFGDefaultButton.setObjectName(u"CFGDefaultButton")
        self.CFGDefaultButton.setGeometry(QRect(100, 750, 61, 25))
        self.CFGDefaultButton.setFont(font12)
        self.w3_Link = QLabel(self.groupBox_12)
        self.w3_Link.setObjectName(u"w3_Link")
        self.w3_Link.setGeometry(QRect(10, 770, 81, 16))
        self.CFGF2_comboBox = QComboBox(self.groupBox_12)
        self.CFGF2_comboBox.setObjectName(u"CFGF2_comboBox")
        self.CFGF2_comboBox.setGeometry(QRect(80, 60, 81, 22))
        self.CFGF2_comboBox.setFont(font12)
        self.CFGF3_comboBox = QComboBox(self.groupBox_12)
        self.CFGF3_comboBox.setObjectName(u"CFGF3_comboBox")
        self.CFGF3_comboBox.setGeometry(QRect(80, 90, 81, 22))
        self.CFGF3_comboBox.setFont(font12)
        self.CFGF4_comboBox = QComboBox(self.groupBox_12)
        self.CFGF4_comboBox.setObjectName(u"CFGF4_comboBox")
        self.CFGF4_comboBox.setGeometry(QRect(80, 120, 81, 22))
        self.CFGF4_comboBox.setFont(font12)
        self.CFGF5_comboBox = QComboBox(self.groupBox_12)
        self.CFGF5_comboBox.setObjectName(u"CFGF5_comboBox")
        self.CFGF5_comboBox.setGeometry(QRect(80, 150, 81, 22))
        self.CFGF5_comboBox.setFont(font12)
        self.CFGF6_comboBox = QComboBox(self.groupBox_12)
        self.CFGF6_comboBox.setObjectName(u"CFGF6_comboBox")
        self.CFGF6_comboBox.setGeometry(QRect(80, 180, 81, 22))
        self.CFGF6_comboBox.setFont(font12)
        self.CFGF7_comboBox = QComboBox(self.groupBox_12)
        self.CFGF7_comboBox.setObjectName(u"CFGF7_comboBox")
        self.CFGF7_comboBox.setGeometry(QRect(80, 210, 81, 22))
        self.CFGF7_comboBox.setFont(font12)
        self.CFGF8_comboBox = QComboBox(self.groupBox_12)
        self.CFGF8_comboBox.setObjectName(u"CFGF8_comboBox")
        self.CFGF8_comboBox.setGeometry(QRect(80, 240, 81, 22))
        self.CFGF8_comboBox.setFont(font12)
        self.CFGF9_comboBox = QComboBox(self.groupBox_12)
        self.CFGF9_comboBox.setObjectName(u"CFGF9_comboBox")
        self.CFGF9_comboBox.setGeometry(QRect(80, 270, 81, 22))
        self.CFGF9_comboBox.setFont(font12)
        self.CFGF10_comboBox = QComboBox(self.groupBox_12)
        self.CFGF10_comboBox.setObjectName(u"CFGF10_comboBox")
        self.CFGF10_comboBox.setGeometry(QRect(80, 300, 81, 22))
        self.CFGF10_comboBox.setFont(font12)
        self.CFGF11_comboBox = QComboBox(self.groupBox_12)
        self.CFGF11_comboBox.setObjectName(u"CFGF11_comboBox")
        self.CFGF11_comboBox.setGeometry(QRect(80, 330, 81, 22))
        self.CFGF11_comboBox.setFont(font12)
        self.CFGF12_comboBox = QComboBox(self.groupBox_12)
        self.CFGF12_comboBox.setObjectName(u"CFGF12_comboBox")
        self.CFGF12_comboBox.setGeometry(QRect(80, 360, 81, 22))
        self.CFGF12_comboBox.setFont(font12)
        self.CFGF13_comboBox = QComboBox(self.groupBox_12)
        self.CFGF13_comboBox.setObjectName(u"CFGF13_comboBox")
        self.CFGF13_comboBox.setGeometry(QRect(80, 390, 81, 22))
        self.CFGF13_comboBox.setFont(font12)
        self.CFGF14_comboBox = QComboBox(self.groupBox_12)
        self.CFGF14_comboBox.setObjectName(u"CFGF14_comboBox")
        self.CFGF14_comboBox.setGeometry(QRect(80, 420, 81, 22))
        self.CFGF14_comboBox.setFont(font12)
        self.CFGF15_comboBox = QComboBox(self.groupBox_12)
        self.CFGF15_comboBox.setObjectName(u"CFGF15_comboBox")
        self.CFGF15_comboBox.setGeometry(QRect(80, 450, 81, 22))
        self.CFGF15_comboBox.setFont(font12)
        self.CFGF16_comboBox = QComboBox(self.groupBox_12)
        self.CFGF16_comboBox.setObjectName(u"CFGF16_comboBox")
        self.CFGF16_comboBox.setGeometry(QRect(80, 480, 81, 22))
        self.CFGF16_comboBox.setFont(font12)
        self.CFGF17_comboBox = QComboBox(self.groupBox_12)
        self.CFGF17_comboBox.setObjectName(u"CFGF17_comboBox")
        self.CFGF17_comboBox.setGeometry(QRect(80, 510, 81, 22))
        self.CFGF17_comboBox.setFont(font12)
        self.CFGF18_comboBox = QComboBox(self.groupBox_12)
        self.CFGF18_comboBox.setObjectName(u"CFGF18_comboBox")
        self.CFGF18_comboBox.setGeometry(QRect(80, 540, 81, 22))
        self.CFGF18_comboBox.setFont(font12)
        self.CFGF19_comboBox = QComboBox(self.groupBox_12)
        self.CFGF19_comboBox.setObjectName(u"CFGF19_comboBox")
        self.CFGF19_comboBox.setGeometry(QRect(80, 570, 81, 22))
        self.CFGF19_comboBox.setFont(font12)
        self.CFGF20_comboBox = QComboBox(self.groupBox_12)
        self.CFGF20_comboBox.setObjectName(u"CFGF20_comboBox")
        self.CFGF20_comboBox.setGeometry(QRect(80, 600, 81, 22))
        self.CFGF20_comboBox.setFont(font12)
        self.CFGF21_comboBox = QComboBox(self.groupBox_12)
        self.CFGF21_comboBox.setObjectName(u"CFGF21_comboBox")
        self.CFGF21_comboBox.setGeometry(QRect(80, 630, 81, 22))
        self.CFGF21_comboBox.setFont(font12)
        self.CFGF22_comboBox = QComboBox(self.groupBox_12)
        self.CFGF22_comboBox.setObjectName(u"CFGF22_comboBox")
        self.CFGF22_comboBox.setGeometry(QRect(80, 660, 81, 22))
        self.CFGF22_comboBox.setFont(font12)
        self.CFGF23_comboBox = QComboBox(self.groupBox_12)
        self.CFGF23_comboBox.setObjectName(u"CFGF23_comboBox")
        self.CFGF23_comboBox.setGeometry(QRect(80, 690, 81, 22))
        self.CFGF23_comboBox.setFont(font12)
        self.ColorJason_label = QLabel(self.groupBox_12)
        self.ColorJason_label.setObjectName(u"ColorJason_label")
        self.ColorJason_label.setGeometry(QRect(10, 747, 81, 16))
        self.groupBox_6 = QGroupBox(self.secondFrame)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(230, 10, 741, 811))
        self.groupBox_6.setFont(font)
        self.groupBox_ExcelGenerator = QGroupBox(self.groupBox_6)
        self.groupBox_ExcelGenerator.setObjectName(u"groupBox_ExcelGenerator")
        self.groupBox_ExcelGenerator.setGeometry(QRect(50, 210, 661, 591))
        self.groupBox_ExcelGenerator.setFont(font)
        self.groupBox = QGroupBox(self.groupBox_ExcelGenerator)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 28, 641, 141))
        self.groupBox.setFont(font1)
        self.comboBoxTcf = QComboBox(self.groupBox)
        self.comboBoxTcf.setObjectName(u"comboBoxTcf")
        self.comboBoxTcf.setGeometry(QRect(10, 24, 581, 24))
        self.genModuleButton = QPushButton(self.groupBox)
        self.genModuleButton.setObjectName(u"genModuleButton")
        self.genModuleButton.setGeometry(QRect(10, 82, 581, 31))
        self.TCF_GRPBY_checkBox = QCheckBox(self.groupBox)
        self.TCF_GRPBY_checkBox.setObjectName(u"TCF_GRPBY_checkBox")
        self.TCF_GRPBY_checkBox.setGeometry(QRect(12, 53, 78, 20))
        self.TCF_Link = QLabel(self.groupBox)
        self.TCF_Link.setObjectName(u"TCF_Link")
        self.TCF_Link.setGeometry(QRect(460, 116, 101, 16))
        self.TCF_Link.setFont(font4)
        self.groupBox_2 = QGroupBox(self.groupBox_ExcelGenerator)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 420, 641, 121))
        self.groupBox_2.setFont(font)
        self.MessageBox2text = QTextEdit(self.groupBox_2)
        self.MessageBox2text.setObjectName(u"MessageBox2text")
        self.MessageBox2text.setGeometry(QRect(10, 20, 611, 91))
        self.groupBox_9 = QGroupBox(self.groupBox_ExcelGenerator)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(10, 175, 641, 151))
        self.groupBox_9.setFont(font1)
        self.comboBoxTSF = QComboBox(self.groupBox_9)
        self.comboBoxTSF.setObjectName(u"comboBoxTSF")
        self.comboBoxTSF.setGeometry(QRect(10, 24, 591, 24))
        self.SpecLineButton = QPushButton(self.groupBox_9)
        self.SpecLineButton.setObjectName(u"SpecLineButton")
        self.SpecLineButton.setGeometry(QRect(10, 90, 591, 31))
        self.ModuleBatchLabel = QLabel(self.groupBox_9)
        self.ModuleBatchLabel.setObjectName(u"ModuleBatchLabel")
        self.ModuleBatchLabel.setGeometry(QRect(13, 65, 261, 16))
        font13 = QFont()
        font13.setPointSize(8)
        font13.setBold(True)
        font13.setUnderline(True)
        font13.setKerning(False)
        self.ModuleBatchLabel.setFont(font13)
        self.ModuleBatchLabel.setAutoFillBackground(False)
        self.TSFNote_label = QLabel(self.groupBox_9)
        self.TSFNote_label.setObjectName(u"TSFNote_label")
        self.TSFNote_label.setGeometry(QRect(20, 126, 361, 21))
        font14 = QFont()
        font14.setFamilies([u"Segoe Print"])
        font14.setPointSize(8)
        font14.setBold(True)
        font14.setKerning(True)
        self.TSFNote_label.setFont(font14)
        self.TSF_Link = QLabel(self.groupBox_9)
        self.TSF_Link.setObjectName(u"TSF_Link")
        self.TSF_Link.setGeometry(QRect(460, 60, 71, 16))
        self.TSF_Link.setFont(font4)
        self.Spec_Link = QLabel(self.groupBox_9)
        self.Spec_Link.setObjectName(u"Spec_Link")
        self.Spec_Link.setGeometry(QRect(460, 126, 71, 16))
        self.Spec_Link.setFont(font4)
        self.triggerSwapFlagcheckBox = QCheckBox(self.groupBox_9)
        self.triggerSwapFlagcheckBox.setObjectName(u"triggerSwapFlagcheckBox")
        self.triggerSwapFlagcheckBox.setGeometry(QRect(300, 60, 111, 20))
        self.triggerSwapFlagcheckBox.setFont(font2)
        self.RefreshButton = QPushButton(self.groupBox_ExcelGenerator)
        self.RefreshButton.setObjectName(u"RefreshButton")
        self.RefreshButton.setGeometry(QRect(500, 360, 151, 51))
        font15 = QFont()
        font15.setPointSize(9)
        font15.setBold(False)
        font15.setKerning(True)
        self.RefreshButton.setFont(font15)
        self.deleteAllButton = QPushButton(self.groupBox_ExcelGenerator)
        self.deleteAllButton.setObjectName(u"deleteAllButton")
        self.deleteAllButton.setGeometry(QRect(250, 550, 391, 31))
        self.deleteAllButton.setFont(font)
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditDelete))
        self.deleteAllButton.setIcon(icon)
        self.deletePartButton = QPushButton(self.groupBox_ExcelGenerator)
        self.deletePartButton.setObjectName(u"deletePartButton")
        self.deletePartButton.setGeometry(QRect(8, 550, 231, 31))
        self.deletePartButton.setFont(font)
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ListRemove))
        self.deletePartButton.setIcon(icon1)
        self.Interpolation_groupBox = QGroupBox(self.groupBox_ExcelGenerator)
        self.Interpolation_groupBox.setObjectName(u"Interpolation_groupBox")
        self.Interpolation_groupBox.setGeometry(QRect(9, 330, 481, 91))
        self.Interpolation_groupBox.setFont(font)
        self.RegenFiles_comboBox = QComboBox(self.Interpolation_groupBox)
        self.RegenFiles_comboBox.setObjectName(u"RegenFiles_comboBox")
        self.RegenFiles_comboBox.setGeometry(QRect(14, 20, 361, 31))
        self.RegenFiles_comboBox.setFont(font15)
        self.Regen_Button = QPushButton(self.Interpolation_groupBox)
        self.Regen_Button.setObjectName(u"Regen_Button")
        self.Regen_Button.setGeometry(QRect(14, 60, 361, 24))
        font16 = QFont()
        font16.setPointSize(8)
        font16.setBold(False)
        font16.setKerning(True)
        self.Regen_Button.setFont(font16)
        self.RegenPath_label = QLabel(self.Interpolation_groupBox)
        self.RegenPath_label.setObjectName(u"RegenPath_label")
        self.RegenPath_label.setGeometry(QRect(390, 24, 81, 16))
        self.Regenoutput_label = QLabel(self.Interpolation_groupBox)
        self.Regenoutput_label.setObjectName(u"Regenoutput_label")
        self.Regenoutput_label.setGeometry(QRect(390, 62, 81, 16))
        self.groupBox_ScriptGenerator = QGroupBox(self.groupBox_6)
        self.groupBox_ScriptGenerator.setObjectName(u"groupBox_ScriptGenerator")
        self.groupBox_ScriptGenerator.setGeometry(QRect(50, 20, 661, 181))
        self.groupBox_ScriptGenerator.setFont(font)
        self.AuthorlineEdit = QLineEdit(self.groupBox_ScriptGenerator)
        self.AuthorlineEdit.setObjectName(u"AuthorlineEdit")
        self.AuthorlineEdit.setGeometry(QRect(110, 30, 511, 31))
        self.TitlelineEdit = QLineEdit(self.groupBox_ScriptGenerator)
        self.TitlelineEdit.setObjectName(u"TitlelineEdit")
        self.TitlelineEdit.setGeometry(QRect(110, 70, 511, 31))
        self.label_18 = QLabel(self.groupBox_ScriptGenerator)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(30, 35, 71, 21))
        self.label_18.setFont(font1)
        self.label_19 = QLabel(self.groupBox_ScriptGenerator)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(30, 75, 71, 16))
        self.label_19.setFont(font1)
        self.label_20 = QLabel(self.groupBox_ScriptGenerator)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 118, 91, 20))
        self.label_20.setFont(font1)
        self.NameineEdit = QLineEdit(self.groupBox_ScriptGenerator)
        self.NameineEdit.setObjectName(u"NameineEdit")
        self.NameineEdit.setGeometry(QRect(110, 110, 511, 31))
        self.tabWidget.addTab(self.tab_2, "")
        self.Updates = QWidget()
        self.Updates.setObjectName(u"Updates")
        self.Update_GroupBox = QGroupBox(self.Updates)
        self.Update_GroupBox.setObjectName(u"Update_GroupBox")
        self.Update_GroupBox.setGeometry(QRect(20, 10, 951, 821))
        font17 = QFont()
        font17.setPointSize(10)
        font17.setBold(True)
        font17.setKerning(True)
        self.Update_GroupBox.setFont(font17)
        self.textEdit_2 = QTextEdit(self.Update_GroupBox)
        self.textEdit_2.setObjectName(u"textEdit_2")
        self.textEdit_2.setGeometry(QRect(10, 20, 931, 791))
        font18 = QFont()
        font18.setPointSize(10)
        font18.setBold(False)
        font18.setKerning(True)
        self.textEdit_2.setFont(font18)
        self.movieLabel = QLabel(self.Update_GroupBox)
        self.movieLabel.setObjectName(u"movieLabel")
        self.movieLabel.setGeometry(QRect(760, 600, 160, 140))
        self.UserFeedback_Link = QLabel(self.Update_GroupBox)
        self.UserFeedback_Link.setObjectName(u"UserFeedback_Link")
        self.UserFeedback_Link.setGeometry(QRect(30, 440, 361, 31))
        self.UserFeedback_Link.setFont(font4)
        self.tabWidget.addTab(self.Updates, "")

        self.retranslateUi(Main)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Main)
    # setupUi

    def retranslateUi(self, Main):
        Main.setWindowTitle(QCoreApplication.translate("Main", u"Form", None))
        self.S_Parameter_groupBox.setTitle(QCoreApplication.translate("Main", u"S-Parameter", None))
        self.Filter_groupBox.setTitle(QCoreApplication.translate("Main", u"Filter", None))
        self.SOnly_checkBox.setText(QCoreApplication.translate("Main", u"S-Only", None))
        self.FOnly_checkBox.setText(QCoreApplication.translate("Main", u"Formula", None))
        self.ModuleCover_groupBox.setTitle(QCoreApplication.translate("Main", u"Features", None))
        self.Module_groupBox.setTitle(QCoreApplication.translate("Main", u"Module/SubCal Trace Extraction | Consolidation", None))
        self.Extract_toolButton.setText(QCoreApplication.translate("Main", u"...", None))
        self.FileType_groupBox.setTitle(QCoreApplication.translate("Main", u"File Setting", None))
        self.compileButton.setText(QCoreApplication.translate("Main", u"Compile", None))
        self.button_ReplaceCFG.setText(QCoreApplication.translate("Main", u"Replace CFG", None))
        self.Overwrite_Link.setText(QCoreApplication.translate("Main", u"..", None))
        self.TestCode.setText(QCoreApplication.translate("Main", u"Test Code:", None))
        self.FileType.setText(QCoreApplication.translate("Main", u"File Type:", None))
        self.dataset_Link.setText(QCoreApplication.translate("Main", u"..", None))
        self.button_HeaderEdit.setText(QCoreApplication.translate("Main", u"Header Edit", None))
        self.RefreshMemory_Button.setText(QCoreApplication.translate("Main", u"Memory", None))
        self.ManualPloting_groupBox.setTitle(QCoreApplication.translate("Main", u"Manual Ploting -File Type", None))
        self.Plot_toolButton.setText(QCoreApplication.translate("Main", u"...", None))
        self.ColorGroupOption_groupBox.setTitle(QCoreApplication.translate("Main", u"Color Grouping Option", None))
        self.label.setText(QCoreApplication.translate("Main", u"Search Group:", None))
        self.ColorCode_lineEdit.setText("")
        self.label_2.setText(QCoreApplication.translate("Main", u"Color Code:", None))
        self.Execute_groupBox.setTitle(QCoreApplication.translate("Main", u"Execute", None))
        self.plotButton.setText(QCoreApplication.translate("Main", u"Trace Plot", None))
        self.LoadButton.setText(QCoreApplication.translate("Main", u"Parameter", None))
        self.XStep.setText(QCoreApplication.translate("Main", u"X-Step:", None))
        self.YStep.setText(QCoreApplication.translate("Main", u"Y-Step:", None))
        self.Selection_groupBox.setTitle(QCoreApplication.translate("Main", u"Selection", None))
        self.cfgFile_checkBox.setText(QCoreApplication.translate("Main", u"CFG File", None))
        self.ByUnit_checkBox.setText(QCoreApplication.translate("Main", u"By Unit", None))
        self.Legend_checkBox.setText(QCoreApplication.translate("Main", u"Legend", None))
        self.ByLot_checkBox.setText(QCoreApplication.translate("Main", u"By Group", None))
        self.cfgUI_checkBox.setText(QCoreApplication.translate("Main", u"CFG UI", None))
        self.SpecLine_checkBox.setText(QCoreApplication.translate("Main", u"SpecLine", None))
        self.PopulatedUnitList_button.setText(QCoreApplication.translate("Main", u"Populated Unit List", None))
        self.ManualHover_checkBox.setText(QCoreApplication.translate("Main", u"Hover", None))
        self.ByUnit_Link.setText(QCoreApplication.translate("Main", u"..", None))
        self.marker_checkBox.setText(QCoreApplication.translate("Main", u"Marker", None))
        self.RegexControl_groupBox.setTitle(QCoreApplication.translate("Main", u"Group Auto", None))
        self.LOTApplyButton.setText(QCoreApplication.translate("Main", u"Apply", None))
        self.Automation_groupBox.setTitle(QCoreApplication.translate("Main", u"Automation", None))
        self.Batch_groupBox.setTitle(QCoreApplication.translate("Main", u"Batch Generator", None))
        self.CapturedButton.setText(QCoreApplication.translate("Main", u"Captured", None))
        self.PPTButton.setText(QCoreApplication.translate("Main", u"Power Point", None))
        self.label_21.setText(QCoreApplication.translate("Main", u"Batch:", None))
        self.AutoSpecLine_checkBox.setText(QCoreApplication.translate("Main", u"Spec Line", None))
        self.ServiceButton.setText(QCoreApplication.translate("Main", u"1 Button Service", None))
        self.RefreshFirstButton.setText(QCoreApplication.translate("Main", u"Refresh Batch", None))
        self.AutoByLot_checkBox.setText(QCoreApplication.translate("Main", u"By Group", None))
        self.AutoByUnit_checkBox.setText(QCoreApplication.translate("Main", u"CFG File", None))
        self.LotModuleButton.setText(QCoreApplication.translate("Main", u"Populated Group List", None))
        self.PPT_Link.setText(QCoreApplication.translate("Main", u"..", None))
        self.Batch_Link.setText(QCoreApplication.translate("Main", u"..", None))
        self.ByLot_Link.setText(QCoreApplication.translate("Main", u"..", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Main", u"Progress Checker", None))
        self.Setting_groupBox.setTitle(QCoreApplication.translate("Main", u"Formula Compiler", None))
        self.Formula_RefreshButton.setText(QCoreApplication.translate("Main", u"Refresh", None))
        self.Formula.setText(QCoreApplication.translate("Main", u"Select:", None))
        self.EditFormulaButton.setText(QCoreApplication.translate("Main", u"Edit", None))
        self.FormulaExecuteButton.setText(QCoreApplication.translate("Main", u"Execute", None))
        self.FreqRange_groupBox.setTitle(QCoreApplication.translate("Main", u"Manual Ploting - Frequency Range(Format: 1,1M,1G)", None))
        self.Start_label.setText(QCoreApplication.translate("Main", u"Start:", None))
        self.Start_label_2.setText(QCoreApplication.translate("Main", u"Stop:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Main", u"S-Parameter", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("Main", u"CFG File Color Reference", None))
        self.colorLabel1.setText(QCoreApplication.translate("Main", u"Group1", None))
        self.colorLabel2.setText(QCoreApplication.translate("Main", u"Group2", None))
        self.colorLabel3.setText(QCoreApplication.translate("Main", u"Group3", None))
        self.colorLabel4.setText(QCoreApplication.translate("Main", u"Group4", None))
        self.colorLabel5.setText(QCoreApplication.translate("Main", u"Group5", None))
        self.colorLabel6.setText(QCoreApplication.translate("Main", u"Group6", None))
        self.colorLabel7.setText(QCoreApplication.translate("Main", u"Group7", None))
        self.colorLabel8.setText(QCoreApplication.translate("Main", u"Group8", None))
        self.colorLabel9.setText(QCoreApplication.translate("Main", u"Group9", None))
        self.colorLabel10.setText(QCoreApplication.translate("Main", u"Group10", None))
        self.colorLabel11.setText(QCoreApplication.translate("Main", u"Group11", None))
        self.colorLabel12.setText(QCoreApplication.translate("Main", u"Group12", None))
        self.colorLabel13.setText(QCoreApplication.translate("Main", u"Group13", None))
        self.colorLabel14.setText(QCoreApplication.translate("Main", u"Group14", None))
        self.colorLabel15.setText(QCoreApplication.translate("Main", u"Group15", None))
        self.colorLabel16.setText(QCoreApplication.translate("Main", u"Group16", None))
        self.colorLabel17.setText(QCoreApplication.translate("Main", u"Group17", None))
        self.colorLabel18.setText(QCoreApplication.translate("Main", u"Group18", None))
        self.colorLabel19.setText(QCoreApplication.translate("Main", u"Group19", None))
        self.colorLabel20.setText(QCoreApplication.translate("Main", u"Group20", None))
        self.colorLabel21.setText(QCoreApplication.translate("Main", u"Group21", None))
        self.colorLabel22.setText(QCoreApplication.translate("Main", u"Group22", None))
        self.colorLabel23.setText(QCoreApplication.translate("Main", u"Group23", None))
        self.CFGDefaultButton.setText(QCoreApplication.translate("Main", u"Default", None))
        self.w3_Link.setText(QCoreApplication.translate("Main", u"..", None))
        self.ColorJason_label.setText(QCoreApplication.translate("Main", u"..", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("Main", u"Configuration", None))
        self.groupBox_ExcelGenerator.setTitle(QCoreApplication.translate("Main", u"Excel Generator", None))
        self.groupBox.setTitle(QCoreApplication.translate("Main", u"Test Condtion File", None))
        self.genModuleButton.setText(QCoreApplication.translate("Main", u"Gen Module File", None))
        self.TCF_GRPBY_checkBox.setText(QCoreApplication.translate("Main", u"Groupby ", None))
        self.TCF_Link.setText(QCoreApplication.translate("Main", u"..", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Main", u"Message Box", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("Main", u"TSF-Spec Line generator", None))
        self.SpecLineButton.setText(QCoreApplication.translate("Main", u"Generate Spec Line", None))
        self.ModuleBatchLabel.setText(QCoreApplication.translate("Main", u"Batch Module:", None))
        self.TSFNote_label.setText(QCoreApplication.translate("Main", u"Notes: TSF Generator Must Syncrhonize with the Batch Scripts", None))
        self.TSF_Link.setText(QCoreApplication.translate("Main", u"..", None))
        self.Spec_Link.setText(QCoreApplication.translate("Main", u"..", None))
        self.triggerSwapFlagcheckBox.setText(QCoreApplication.translate("Main", u"triggerSwapFlag", None))
        self.RefreshButton.setText(QCoreApplication.translate("Main", u"Refresh ComboBox", None))
        self.deleteAllButton.setText(QCoreApplication.translate("Main", u"Delete All Generate Files", None))
        self.deletePartButton.setText(QCoreApplication.translate("Main", u"Delete Batch / Spec ", None))
        self.Interpolation_groupBox.setTitle(QCoreApplication.translate("Main", u"Interpolation", None))
        self.Regen_Button.setText(QCoreApplication.translate("Main", u"REGEN", None))
        self.RegenPath_label.setText(QCoreApplication.translate("Main", u"..", None))
        self.Regenoutput_label.setText(QCoreApplication.translate("Main", u"..", None))
        self.groupBox_ScriptGenerator.setTitle(QCoreApplication.translate("Main", u"Power Point information", None))
        self.AuthorlineEdit.setText(QCoreApplication.translate("Main", u"NPI Penang", None))
        self.TitlelineEdit.setText(QCoreApplication.translate("Main", u"Module -Trace", None))
        self.label_18.setText(QCoreApplication.translate("Main", u"Author:", None))
        self.label_19.setText(QCoreApplication.translate("Main", u"Tittle:", None))
        self.label_20.setText(QCoreApplication.translate("Main", u"TemplateName:", None))
        self.NameineEdit.setText(QCoreApplication.translate("Main", u"Output", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Main", u"Configuration", None))
        self.Update_GroupBox.setTitle(QCoreApplication.translate("Main", u"Official Released 7.0.0.0", None))
        self.textEdit_2.setHtml(QCoreApplication.translate("Main", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:700; text-decoration: underline;\">Main changes:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1) Step Scaling and Range Customization on plot for both Manual/Auto.<br />2) Marker Implementation both Frequency range and magnitude ploting at Manual Ploting, support singl"
                        "e point,single Line,Range Line.<br />3) Inherit  feature from lazyworm by Implement Interpolation feature that cover RIPPLE,MAG and FREQ feature.<br />4) Bug Fixing at SNP files.<br />5) Color Customization on the color selection in Manual Ploting follow PADMA, and Add Eye Drop feature to copy color from platform surface.<br />6) Implementation on Progress Bar by tracking all the features during execution.<br />7) SNP Overall file compilation, for FCM use case.<br />8) Memory Record for Compilation/Manual Plot User Setting.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /><span style=\" font-size:11pt; font-weight:700; text-decoration: underline;\">KeyNote:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#ff0000;\">1) Spec Line feature still under investigation based on Format Standardization, not align"
                        " with GE Header. (On-Hold)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; font-style:italic;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:700; text-decoration: underline;\">Feedback Collection</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&quot;I've created a Google Sheet where you can provide feedback and track the progress of your requests.&quot;</p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Action:</span> Please add your suggestio"
                        "ns to the <span style=\" font-weight:700;\">&quot;Improvement Items&quot;</span> and <span style=\" font-weight:700;\">&quot;Comments&quot;</span> columns.</li>\n"
"<li style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Details:</span> Kindly include your name in case I need to follow up.</li>\n"
"<li style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Timeline:</span> I will review and prioritize all items. My goal is to address them within one month of each software release, though high-risk issues may require additional time.</li></ul>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; font-style:italic;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; marg"
                        "in-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.movieLabel.setText(QCoreApplication.translate("Main", u"TextLabel", None))
        self.UserFeedback_Link.setText(QCoreApplication.translate("Main", u"..", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Updates), QCoreApplication.translate("Main", u"Updates", None))
    # retranslateUi

